import type { Product } from "./types";

const material = "35% silk, 65% wool";

const pieceDetails = [
  material,
  "Rolled edges",
  "Signed with the JB monogram",
  "Folds up to seven ways",
  "One of ten squares in the Pocket Power box",
];

// Square names are working titles taken from colour and pattern. Rename freely.
// `tile-*` images are cut from group shots by scripts/prepare-photos.mjs.
export const products: Product[] = [
  {
    slug: "pocket-power",
    kind: "set",
    name: "Pocket Power",
    descriptor: "The box of ten",
    summary: "One box. Ten pocket squares. Designed to make you stand out.",
    description: [
      "Pocket Power is the first collection from Joshua Black: ten pocket squares, each a different design, kept together in an engraved wooden box.",
      "The cloth is a silk-wool blend. It is soft, yet structured enough to hold its fold in your pocket.",
      "Every square can be folded up to seven ways, so the same ten pieces look different from one occasion to the next.",
    ],
    details: [
      "Ten pocket squares, ten designs",
      material,
      "Rolled edges",
      "Each square signed with the JB monogram",
      "Engraved wooden box with a metal clasp",
      "Each square folds up to seven ways",
    ],
    care: [],
    tile: { id: "pp-box-open" },
    gallery: [
      { id: "pp-box-open" },
      { id: "pp-fan" },
      { id: "pp-drape" },
      { id: "pp-box-stack" },
      { id: "pp-rail" },
      { id: "pp-box-engraved" },
      { id: "pp-founder-box" },
    ],
  },
  {
    slug: "emerald-medallion",
    kind: "piece",
    number: "01",
    name: "Emerald Medallion",
    descriptor: "Emerald green",
    summary: "An emerald ground carrying a framed medallion in gold, red and blue.",
    description: [
      "Deep emerald, with an ornamental medallion set inside a gold frame. The richest pattern in the box, and the one that reads from across a room.",
    ],
    details: pieceDetails,
    care: [],
    tile: { id: "tile-emerald" },
    gallery: [{ id: "pp-rail" }, { id: "pp-closeup" }, { id: "pp-box-open" }, { id: "pp-fan" }],
  },
  {
    slug: "midnight-diamond",
    kind: "piece",
    number: "02",
    name: "Midnight Diamond",
    descriptor: "Midnight navy",
    summary: "Navy scattered with small blue diamonds and white dots, edged in tan.",
    description: [
      "A quiet geometric: blue diamonds and white pin dots on midnight navy, framed by a plain navy border and a tan rolled edge.",
    ],
    details: pieceDetails,
    care: [],
    tile: { id: "tile-midnight" },
    gallery: [{ id: "pp-rail" }, { id: "pp-closeup" }, { id: "pp-fan" }],
  },
  {
    slug: "black-paisley",
    kind: "piece",
    number: "03",
    name: "Black Paisley",
    descriptor: "Black and gold",
    summary: "Gold and cream paisley drifting across black, finished with a bronze edge.",
    description: [
      "Paisley in gold and cream on a black ground, held inside a bronze line and a bronze rolled edge.",
    ],
    details: pieceDetails,
    care: [],
    tile: { id: "tile-black-paisley" },
    gallery: [{ id: "pp-rail" }, { id: "pp-fan" }, { id: "pp-drape" }],
  },
  {
    slug: "noir-botanical",
    kind: "piece",
    number: "04",
    name: "Noir Botanical",
    descriptor: "Black and teal",
    summary: "Teal fronds and small flowers on black, with a woven bronze edge.",
    description: [
      "A botanical print in teal, green and gold on black. The bronze edge is woven rather than plain, and catches the light as the square moves.",
    ],
    details: pieceDetails,
    care: [],
    tile: { id: "pp-noir" },
    gallery: [{ id: "pp-noir" }, { id: "pp-drape" }],
  },
  {
    slug: "violet-lattice",
    kind: "piece",
    number: "05",
    name: "Violet Lattice",
    descriptor: "Violet and midnight",
    summary: "A lattice of violet flowers on midnight, framed by a fine gold line.",
    description: [
      "Violet four-petal flowers repeat across a midnight ground, closed in by a gold line and a wide plain border.",
    ],
    details: pieceDetails,
    care: [],
    tile: { id: "pp-box-stack" },
    gallery: [{ id: "pp-box-stack" }, { id: "pp-fan" }],
  },
  {
    slug: "oxblood-baroque",
    kind: "piece",
    number: "06",
    name: "Oxblood Baroque",
    descriptor: "Oxblood and gold",
    summary: "Gold scrollwork with blue and green accents on a deep oxblood ground.",
    description: [
      "Scrolling gold ornament, picked out in blue and green, on oxblood. A wide plain border keeps the pattern in check.",
    ],
    details: pieceDetails,
    care: [],
    tile: { id: "pp-rust" },
    gallery: [{ id: "pp-rust" }, { id: "pp-fan" }, { id: "pp-drape" }],
  },
  {
    slug: "champagne",
    kind: "piece",
    number: "07",
    name: "Champagne",
    descriptor: "Champagne",
    summary: "The plain square of the ten: a single tone of champagne with a soft sheen.",
    description: [
      "No pattern, only colour and sheen. The square to reach for when the tie is already doing the talking.",
    ],
    details: pieceDetails,
    care: [],
    tile: { id: "tile-champagne" },
    gallery: [{ id: "pp-fan" }, { id: "pp-box-open" }],
  },
  {
    slug: "aubergine-paisley",
    kind: "piece",
    number: "08",
    name: "Aubergine Paisley",
    descriptor: "Aubergine",
    summary: "Lilac paisley outlined in gold on a dark aubergine ground.",
    description: [
      "Lilac paisley, traced in gold, on aubergine. A bronze line and bronze edge tie it to the rest of the box.",
    ],
    details: pieceDetails,
    care: [],
    tile: { id: "tile-aubergine" },
    gallery: [{ id: "pp-drape" }, { id: "pp-box-open" }],
    needsPhoto: true,
  },
  {
    slug: "slate-linework",
    kind: "piece",
    number: "09",
    name: "Slate Linework",
    descriptor: "Slate blue",
    summary: "Fine black linework drawn over slate blue.",
    description: [
      "A drawn pattern in black line on slate blue, the coolest tone among the ten.",
    ],
    details: pieceDetails,
    care: [],
    tile: { id: "tile-slate" },
    gallery: [{ id: "pp-drape" }, { id: "pp-box-open" }],
    needsPhoto: true,
  },
  {
    slug: "the-tenth",
    kind: "piece",
    number: "10",
    name: "The Tenth",
    descriptor: "In the box",
    summary: "The tenth square, waiting in the box.",
    description: [
      "Ten squares leave in every box. This one is yet to be photographed on its own.",
    ],
    details: pieceDetails,
    care: [],
    tile: { id: "tile-tenth" },
    gallery: [{ id: "pp-box-open" }, { id: "pp-drape" }],
    needsPhoto: true,
  },
];
